philburk/pforth

- build/unix/Makefile
Signed-off-by: Phil Burk <philburk@mobileer.com>
> Fix Makefile for Mac clang

- csrc/pf_guts.h
- csrc/pf_inner.c
- csrc/pfcompil.c
- fth/t_file.fth
* csrc/pf_guts.h (cforth_primitive_ids): Add ID_FILE_FLUSH, remove
ID_RESERVED13.
(THROW_FLUSH_FILE): New.
* csrc/pf_inner.c (pfCatch): Add case for ID_FILE_FLUSH.
* csrc/pfcompil.c (pfBuildDictionary): Add FLUSH-FILE.
* fth/t_file.fth (FLUSH-FILE): Remove stub definition.
> Implement FLUSH-FILE

- fth/misc2.fth
> added ? word as a convenience

- .gitignore
- build/win32/vs2017/pforth.sln
- build/win32/vs2017/pforth_main.vcxproj
- build/win32/vs2017/pforth_main.vcxproj.filters
- csrc/pf_inner.c
- csrc/pf_save.c
- csrc/pfinnrfp.h
Add support for VS 2017 and address some compiler warnings emitted by cl.exe
> Support VS 2017

- csrc/pf_guts.h
- readme.txt
- releases.txt
> Bump to V28

- build/win32/vs2017/pforth.sln
- build/win32/vs2017/pforth_main.vcxproj
- csrc/pf_core.c
- csrc/pf_guts.h
- csrc/pf_inner.c
- csrc/pf_main.c
- csrc/pf_save.c
- csrc/pf_text.c
- csrc/pf_text.h
- csrc/pfcompil.c
- csrc/pfinnrfp.h
- csrc/pforth.h
Address some issues with 64-bit on Windows. Most were related to compiler warnings, but one was an issue with floating point.
> Windows and 64-bit

- csrc/pf_core.c
- csrc/pf_inner.c
- csrc/pf_io.h
- csrc/pfcompil.c
Fix some 64-bit usage for Mac.
ASCII EOT forces a BYE and exit from Forth.
> Use from juce

- csrc/pf_inner.c
> csrc: fix stack diagram for BIN

- .github/workflows/cmake.yml
Also test t_locals.fth and t_alloc.fth
> test: show test output

- fth/condcomp.fth
- fth/t_corex.fth
> Add [DEFINED] and [UNDEFINED]

- fth/floats.fth
- fth/loadp4th.fth
- fth/structure.fth
- fth/t_corex.fth
- fth/t_floats.fth
BEGIN-STRUCTURE and END-STRUCTURE
+FIELD FIELD: and CFIELD:
FFIELD: for float members
> Add ANS structure support

- csrc/pf_inner.c
> Add CR to tick

- fth/t_file.fth
> Change tests for S"

- fth/t_floats.fth
The structure tests in t_floats.fth was broken.
Fixes #142
> Fix broken test for 32-bit

- csrc/pf_float.h
- csrc/pfinnrfp.h
Was log(x)+1
Now log(x+1)
Fixes #155
> Fix FLNP1 calculation

- platforms/unix/Makefile
For Address Sanitization, for debugging #174
> Add ASANOPTS to Makefile

- csrc/stdio/pf_fileio_stdio.c
This should fix issue #171
Tested on virtual machines for NetBSD + FreeBsd + Linux (Manjaro).
> suggested fix for issue #171

- csrc/stdio/pf_fileio_stdio.c
> Cleanup indentation in pf_fileio_stdio.c

- fth/floats.fth
- fth/t_floats.fth
Was calling FLOG with negative numbers!
Add a test to catch this.
Fixes #199
> Fix F. calling FLOG illegally

- fth/t_include.fth
- platforms/unix/Makefile
Test: make clean && make ASAN=1 test
Fixes #178
> Add test for long line bug #174
